name: wazo-calld-new-line-status
namespace: wazocommunication
version: 1.0.0
author: Wazo authors
display_name: Fix line status after creation
plugin_format_version: 1
min_wazo_version: 24.10
max_wazo_version: 24.11
tags:
  - calls
  - lines
homepage: https://github.com/wazo-communication/wazo-calld-new-line-status-plugin
